### ISSUE TITLE
Are versions of the vpnbook script available for vpnme.com and freevpnme.com?

### ISSUE THREAD

**Issue by famewolf** [ryanniehaus/useful_scripts#1]
Hi,

Sorry to impose.   I've been staring at your script which works SO WELL for vpnbook...it's really made my life easier however vpnbook for very good reasons prevents use of p2p apps where vpnme and freevpnme do not.  I find myself using bittorrent sync and syncthing (open source alternative to btsync...not really ready for primetime)....so I'm wondering if you have versions which would work on these other sites?   I attempted to create one but I still am unsure how your script knows which user and password to pull....vpnme also for example puts the user/pass on one page and the configs on another.  Thanks for taking the time to read this

**Comment by famewolf** [comment]
I made modified scripts which also work for www.freevpn.me and www.vpnkeys.com however I cannot get sed to remove the leading "space" in front of the username and password.   I'm happy to share the scripts if you think they'd be useful.  For now I just manually remove the space on vpnkeys.

**Comment by ryanniehaus** [comment]
@famewolf: This would be useful.  I might be able to help fix up your scripts if you share.
If they are similar enough to my scripts, perhaps you could fork mine and submit your mods that way.

Thanks for this input.

I can try to explain how the user/pass parsing works:

The first part finds the line containing Username in the file:
cat index.html | grep "Username:"

The next part removes all whitespace in the line:
| sed 's/[ \t]+//g' 

This part removes all html tags
| sed 's/<[^>]+>//g' 

I don't remember why I sort it (should just be one line at this point)
| sort -du 

This part changes line endings to unix so the sed with the line start indicator works correctly, the sed removes the "Username:" from the start of the line, and line endings are changed back again and dumped as the first line of the username_password.txt file
| dos2unix | sed 's/^Username://' | unix2dos > username_password.txt

The password line is the same, but >> appends it as the next line of the file

**Comment by famewolf** [comment]
I'm happy to share the scripts...the vpnkeys one is the one modified the most because the website had non printable characters that had to be stripped out.  I also added some filtering to prevent duplicate user-pass-auth statements from appearing in the .ovpn files when the script is ran multiple times...both vpnbook and vpnkeys were doing that but I still get TWO instead of one because one has a "^M" at the end that the eliminate dupe command considers unique.   In any case glad to share.

The files are available at http://www19.zippyshare.com/v/bw41FC1Y/file.html

Oh the sort -du was there because on the vpnbook page the user/pass is listed twice..once for pptp and once for ovpn so you did have dupes.  The one I've given up on trying is https://www.vpnme.me/freevpn.html   3 side by side server/user/pass followed by 3 more and the zip file is not on the page, only linked to.  

I just changed the zip file to one that includes your fix as well as correcting the getfreevpn.me script which had a leading space or unprintable character in front of the password.  I had to use sed -n '1p'  there to ensure we got the 2nd username and password since the username is different between pptp and openvpn.

**Comment by ryanniehaus** [comment]
@famewolf:
I've merged your changes into my main script.
I've done the Username/Password parsing a bit differently in order to handle non-ASCII index.html files.
This method also avoids random control codes that your friend was filtering out with the sed statement by converting to ASCII.  (Some of these providers were serving pages that were encoded using UTF-8).
I've also made it so the .ovpn file modification time is preserved so the zip mod time checking actually means something.

I still need to attempt adding vpnme.me/freevpn.html, but I'm up for the challenge :)

Let me know if you have any issues with what I've committed so far.

**Comment by famewolf** [comment]
I ran into this issue on first run.....not sure if it's something that should be set.  I didn't make the files 644. Might just be because my vpn dir is on a nas storage area so all the pc's in house can access it.

Server file no newer than local file ‘VPNBook.com-OpenVPN-DE1.zip’ -- not retrieving.

Archive:  VPNBook.com-OpenVPN-CA1.zip
Archive:  VPNBook.com-OpenVPN-DE1.zip
Archive:  VPNBook.com-OpenVPN-Euro1.zip
Archive:  VPNBook.com-OpenVPN-Euro2.zip
Archive:  VPNBook.com-OpenVPN-US1.zip
Archive:  VPNBook.com-OpenVPN-US2.zip
mv: try to overwrite ‘vpnbook-ca1-tcp80.ovpn’, overriding mode 0644 (rw-r--r--)? y
mv: try to overwrite ‘vpnbook-ca1-tcp443.ovpn’, overriding mode 0644 (rw-r--r--)? y
mv: try to overwrite ‘vpnbook-euro2-tcp80.ovpn’, overriding mode 0644 (rw-r--r--)? y
mv: try to overwrite ‘vpnbook-us1-tcp443.ovpn’, overriding mode 0644 (rw-r--r--)? y
mv: try to overwrite ‘vpnbook-euro1-tcp80.ovpn’, overriding mode 0644 (rw-r--r--)? y
mv: try to overwrite ‘vpnbook-euro1-udp53.ovpn’, overriding mode 0644 (rw-r--r--)? y
mv: try to overwrite ‘vpnbook-euro2-udp53.ovpn’, overriding mode 0644 (rw-r--r--)? y
mv: try to overwrite ‘vpnbook-de233-udp53.ovpn’, overriding mode 0644 (rw-r--r--)? y
mv: try to overwrite ‘vpnbook-euro1-udp25000.ovpn’, overriding mode 0644 (rw-r--r--)? y
mv: try to overwrite ‘vpnbook-ca1-udp25000.ovpn’, overriding mode 0644 (rw-r--r--)? y
mv: try to overwrite ‘vpnbook-us1-udp53.ovpn’, overriding mode 0644 (rw-r--r--)? y
mv: try to overwrite ‘vpnbook-euro1-tcp443.ovpn’, overriding mode 0644 (rw-r--r--)? y
mv: try to overwrite ‘vpnbook-us2-tcp443.ovpn’, overriding mode 0644 (rw-r--r--)? y
mv: try to overwrite ‘vpnbook-de233-tcp443.ovpn’, overriding mode 0644 (rw-r--r--)? 
etc............

**Comment by ryanniehaus** [comment]
@famewolf:
Not sure why your permissions are set differently, but I added a -f flag to the mv command so it shouldn't ask you anymore.

**Comment by famewolf** [comment]
I'm not sure if this is something you want to address or not.   It's not an issue for me but might be for systems with multiple users?

WARNING: file 'username_password.txt' is group or others accessible

**Comment by famewolf** [comment]
Oh I didn't mention them but strictly as an FYI there is also freevpnsoftware.net and http://www.vpngate.net/   both of which do not use username/password.  The only problem with vpngate is that even when you find a handful that work the NEXT time you want to use them they are defunct.  When you visit the website it pulls up a random amount of nodes for you to use.

**Comment by ryanniehaus** [comment]
@famewolf:
vpnme.me data is now parsed by the script.  It was a larger change.
Now it's fixed again

**Comment by famewolf** [comment]
If vpnme.me parsing is supposed to be 100% you may want to relook at the *.ovpn files at the end of the KEY parm...it repeats a 2nd time with a corrupted user/pass auth line.

</key>_username_password.txt
client
auth SHA1
dev tun
proto udp
....

**Comment by ryanniehaus** [comment]
@famewolf: Are you getting any errors when this happens??  I'm not getting that problem.  Also, are you sure you're using the latest version?

**Comment by famewolf** [comment]
I had pulled the code down right before I ran it but perhaps it didn't like something I had in the vpnme dir.......I deleted the www.vpnme.me dir and just to be safe grabbed the code again....ran it...looked fine...ran it a second time to be certain and it again looked fine so chalk this one up to a false alarm or something glitchy.   You make the parsing look so easy.

**Comment by famewolf** [comment]
I guess the only addition I would request is a method to overwrite what directory to use as when ran from cron.daily it tries to put the zip files in the /etc/cron.daily dir.....I hardcoded the dir in the previous version.

**Comment by famewolf** [comment]
I just tried to connect to vpnme_ca_udp1194.ovpn and got an auth failed...after reviewing the 192.99.240.185_username_password.txt file associated with it in the ovpn it seems to have the password for the pptp server and not the openvpn one.   2nd set of 3 is openvpn.  

I verified the other two are also the pptp password and I assume user but the user is the same in both places.

**Comment by ryanniehaus** [comment]
Hmm... I wonder what I missed with that.  Thanks for all the feedback!

**Comment by ryanniehaus** [comment]
I see... it looks like I made a typo, which caused me to parse the wrong table.  My server matching stuff won't work the same, so I'll have to make quite a few changes I think.  Oh, well.  I'll let you know when I've figured it out.

**Comment by ryanniehaus** [comment]
@famewolf:
Fixed, and verified as working.
Please close this issue if working for you.

If you want any other providers added, please create separate issues.

**Comment by famewolf** [comment]
Double checked and closing.  Thanks for the multitude of changes.
